const mongoose = require("mongoose");

const food = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    required: true,
  },
  category: {
    type: String,
    enums: [
      "Entrees",
      "Main Courses",
      "Mains",
      "Specialties",
      "Grilled",
      "Roasted",
      "Baked",
      "Fried",
      "Stir-Fried",
      "Sauteed",
      "Pan-Seared",
      "Steamed",
      "Braised",
      "Stews",
      "Curries",
      "Tandoori",
      "Kebabs",
      "Wraps",
      "Sandwiches",
      "Burgers",
      "Pizzas",
      "Pastas",
      "Noodles",
      "Rice Bowls",
      "Sushi",
      "Sashimi",
      "Tacos",
      "Burritos",
      "Quesadillas",
      "Fajitas",
      "Enchiladas",
      "Tapenade",
      "Dips",
      "Spreads",
      "Cheese Platter",
      "Charcuterie",
      "Mezze",
      "Sides",
      "Vegetables",
      "Potatoes",
      "Grains",
      "Legumes",
      "Desserts",
      "Pastries",
      "Cakes",
      "Pies",
      "Ice Cream",
      "Sorbet",
      "Gelato",
      "Beverages",
      "Cocktails",
      "Mocktails",
      "Smoothies",
      "Milkshakes",
      "Fresh Juices",
      "Hot Drinks",
      "Coffee",
      "Tea",
      "Infusions",
      "Breakfast",
      "Brunch",
      "Lunch",
      "Dinner",
      "Kids Menu",
      "Specials",
    ],
  },
  quantity: {
    type: Number,
    required: true,
    default: 0,
  },
  img_url: {
    type: String,
  },
  hotel_id: {
    type: Schema.Types.ObjectId,
    ref: "Hotel",
    required: true,
  },
});

module.exports = new mongoose.model("Food", food);
